
# 1.  Value Iteration

In [3]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mp
from random import random

In [39]:
def Actions(x_pos,y_pos):           
    x_max = 4                                
    y_max = 3
    directions = np.array([0,0,0,0,1])      #["Up", "Left", "Down", "Right", "DoNothing"]
    if((x_pos >=0 and x_pos <=x_max) and (y_pos >=0 and y_pos <=y_max)):  
        if(y_pos-0)>0:                    
            directions[0] = 1
        if(x_pos-0)>0:
            directions[1] = 1
        if(y_max-y_pos)>0:
            directions[2] = 1
        if(x_max-x_pos)>0:
            directions[3] = 1
        return directions
    else:
        print("Error in direction values")        
        
def calculate(g_x,j_n):                          
    alpha = 0.9900
    ans = g_x +alpha*(j_n)
    return ans


In [40]:
color_world = [[0,0,1,0,-1],               #grey box is np.inf
              [0,np.inf,1,0,10],
              [0,10,np.inf,1,0],
              [1,0,0,10,-1]]

prev_world = np.array(color_world)
color_world = np.array(color_world)           #this is the main version updated
world_copy = np.copy(color_world)             # keep original version of color_world

def VI(color_world):
    change = 3                              #Arbitrary value used to initialize "change"
    runtime = 0                           #number of runs
    threshold = 0.000001

    policy = color_world.tolist()         #initialize control matrix
    while change > threshold:    
        prev_world = np.copy(color_world)         #get previous iteration values
        for i in range(len(color_world)):           #y iteration
            for j in range(len(color_world[0])):    #x iteration
                if color_world[i][j] != np.inf:      # this line is just to avoid calculations with np.inf
                    dr = ["GoUp", "GoLeft", "GoDown", "GoRight", "DoNothing"] #
                    directions = Actions(j,i)      #x,y  
                    
                    #calculate for DoNothing
                    val_hold = np.zeros(5)
                    value = calculate(world_copy[i][j],prev_world[i][j])   
                    val_hold[4] = value          
                    
                    # calculate value for Up
                    if (directions[0] == 1):     
                        value = calculate(world_copy[i][j],prev_world[i-1][j])
                        val_hold[0]= value
                        
                    # calculate value for Left
                    if (directions[1] == 1):     
                        value = calculate(world_copy[i][j],prev_world[i][j-1])
                        val_hold[1] = value
                        
                    # calculate value for Down
                    if (directions[2] == 1):     
                        value = calculate(world_copy[i][j],prev_world[i+1][j])
                        val_hold[2] = value
                        
                    # calculate value for Right    
                    if (directions[3] == 1):     
                        value = calculate(world_copy[i][j],prev_world[i][j+1])
                        val_hold[3] = value 
                    
                    #find the min value
                    min_val = min(val_hold)        
                    if min_val == val_hold[4]:
                        policy[i][j] = dr[4]  
                    else:
                        ind = np.where(val_hold == min_val)
                        policy[i][j] = dr[ind[0][0]]
                        
                    color_world[i][j] = min_val     
        runtime += 1     
        change = abs(color_world[i][j])-abs(prev_world[i][j])
    
    policy = np.array(policy)
        
    print("\n The original cost values:\n",world_copy)
    print("\n Optimal Policy:\n",policy)
    print("\n Value Function:\n",color_world)
    print("\n The number of iterations for convergence:",runtime)


In [41]:
VI(color_world)


 The original cost values:
 [[ 0.  0.  1.  0. -1.]
 [ 0. inf  1.  0. 10.]
 [ 0. 10. inf  1.  0.]
 [ 1.  0.  0. 10. -1.]]

 Optimal Policy:
 [['GoRight' 'GoRight' 'GoRight' 'GoRight' 'DoNothing']
 ['GoUp' 'inf' 'GoRight' 'GoUp' 'GoUp']
 ['GoUp' 'GoLeft' 'inf' 'GoRight' 'GoDown']
 ['GoUp' 'GoLeft' 'GoLeft' 'GoRight' 'DoNothing']]

 Value Function:
 [[-95.07940237 -96.03980137 -97.00990137 -98.99990137 -99.99990137]
 [-94.12860736          inf -96.02980137 -98.00990137 -88.99990137]
 [-93.1873203  -82.25544611          inf -97.00990137 -98.99990137]
 [-91.25544611 -90.34289066 -89.43946077 -88.99990137 -99.99990137]]

 The number of iterations for convergence: 1375


# 3. Policy Iteration v/s Value Iteration

In case of Policy iteration, we perform policy evaluation and policy improvement, and these two are repeated iteratively until policy converges.
In case of Value iteration includes, we find optimal value function and do one policy extraction. There is no repeat of the two because once the value function is optimal, then the policy out of it should also be optimal (i.e. converged).
Thse algorithms have similar approach, but policy iteration is faster than value iteration with time complexity of $O(S^2)$ per iteration,and converges more quickly than a value function. Value Iteration is slow – $O(S^2A)$.
Value iteration is simpler but its computationally heavy. Whereas, Policy iteration is complicated but its computationally cheap w.r.t value iteration.